version: 2

updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      semver-patch-days: 7
      semver-minor-days: 7
      semver-major-days: 30
      default-days: 7
